### ISSUE TITLE
Fexinidazole?

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMycetoma/What-other-molecules-to-screen#11]
DNDI seems to have basically gotten worldwide approval of this drug for sleeping sickness - Have we screened this against mycetoma? I don't see any spreadsheet data saying so!

Would be a miracle if it's potent but hey it's worth a shot @OpenSourceMycetoma/corecontrib

**Comment by bebi78** [comment]
@MFernflower I made several antiparasitic hydrazones and imines of that type of drugs.
https://www.mdpi.com/2218-0532/91/3/44

**Comment by MFernflower** [comment]
Can those samples of fexi and derivatives be sent to Wendy? @bebi78

**Comment by bebi78** [comment]
@MFernflower It's no problem to send some (4 or 5) of the most active ones.

**Comment by bebi78** [comment]
@MFernflower Fexinidazole and other nitroimidazoles were inactive, it was tested in the niclosamide paper (see link) of @wwjvdsande 
Sorry, was also misguided by the time ´´12 noon UK´´ for the meeting yesterday.
https://www.mdpi.com/1420-3049/26/13/4005
